stages:
  - test
  - build

cache: &global_cache
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
  policy: pull-push

before_script:
  # Install ssh-agent if not already installed, it is required by Docker.
  # (change apt-get to yum if you use a CentOS-based image)
  - "which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )"
  # Run ssh-agent (inside the build environment)
  - eval $(ssh-agent -s)
  # Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - yarn config set registry https://registry.npm.taobao.org/

################## 开发环境 ###################
job:BuildDevelopTooqingStudio:
  cache:
    <<: *global_cache
    policy: pull
  stage: build
  only:
    - /^develop-.*$/
  tags:
    - qing-edt-builder
  script:
    - yarn install
    - npm rebuild node-sass
    - yarn upgrade @PixelPai/game-core game-capsule pkth5_resource_tools net-socket-packet pixelpai_proto
    - yarn run package:windows:develop
    - node upload-app.js develop

#########################################

################## 测试环境 ###################
job:BuildReleaseTooqingStudio:
  cache:
    <<: *global_cache
    policy: pull
  stage: build
  only:
    - /^release-.*$/
  tags:
    - qing-edt-builder
  script:
    - yarn install
    - npm rebuild node-sass
    - yarn upgrade @PixelPai/game-core game-capsule pkth5_resource_tools net-socket-packet pixelpai_proto
    - yarn run package:windows:release
    - node upload-app.js release

#########################################

################## 生产环境 ###################
job:BuildProductionTooqingStudio:
  cache:
    <<: *global_cache
    policy: pull
  stage: build
  only:
    - /^production-.*$/
  tags:
    - qing-edt-builder
  script:
    - yarn install
    - npm rebuild node-sass
    - yarn upgrade @PixelPai/game-core game-capsule pkth5_resource_tools net-socket-packet pixelpai_proto
    - yarn run package:windows:production
    - node upload-app.js production
#########################################
