import { AfterViewInit, ElementRef, OnDestroy, OnInit, Type, Compiler, Injector, ViewContainerRef } from "@angular/core";
import { ContextService } from "./core/services";
import { DialogService } from "primeng/dynamicdialog";
import { MenuComponent } from "workbench/app/slots/menu/menu.component";
import { ActivitybarComponent } from "workbench/app/slots/activitybar/activitybar.component";
import { HttpClient } from "@angular/common/http";
export declare class AppComponent implements OnInit, AfterViewInit, OnDestroy {
    private http;
    private dialogService;
    private contextService;
    private compiler;
    private injector;
    content: ViewContainerRef;
    private _destroy;
    private plugins;
    constructor(http: HttpClient, dialogService: DialogService, contextService: ContextService, compiler: Compiler, injector: Injector);
    workbenchMenu: ElementRef<MenuComponent>;
    workbenchActivitybar: ElementRef<ActivitybarComponent>;
    workbenchExplorer: ElementRef;
    workbenchEditor: ElementRef;
    workbenchExtensions: ElementRef;
    workbenchStatusbar: ElementRef;
    ngOnInit(): void;
    ngAfterViewInit(): void;
    private loadPlugins;
    private createPlugin;
    registSlotUi(config: any): void;
    registComponentEvent(): void;
    openDialog(componentType: Type<any>): void;
    ngOnDestroy(): void;
}
